### PR TITLE
added Linux Mint 15 / Ubuntu 13.04 Installation guide

### PR DESCRIPTION
**Pull request by kaefert**

### CODE REVIEW

**Comment by pdostal** [comment]
Hello @kaefert,

could you please reopen this PR against [pdostal/gnome-shell-mousewheel-zoom](https://github.com/pdostal/gnome-shell-mousewheel-zoom) repository?

This project is still useful and I would like to keep it alive :smile:

**Comment by kaefert** [comment]
Isn't that functionality inbaked in all the current cinnamon releases? so you don't need an extension for it anymore?

**Comment by pdostal** [comment]
I use it in Gnome Shell where it isn't implemented yet.
So I'm trying to keep this project alive, I opened #25 just now.

But since I found your how-to useful I'd like to merge it into mine branch.
My plan is to make the repository more clear and gather more information.

This feature is kinda key for me as for visually impaired.
I also want to stick with Gnome which is recommended at SUSE.

**Comment by kaefert** [comment]
Okey. I copied the change  to a pull request in your repository, see https://github.com/pdostal/gnome-shell-mousewheel-zoom/pull/1

**Comment by pdostal** [comment]
Thank you. I still hope we'll be able to merge it here one day.

**Comment by pdostal** [comment]
OK, can you please close this PR? It was already merged :smile:

**Pull request closed without merging**
